// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP_KYtLoBz0YOt9kmgaqZCyOx1HVMuKRc',
    appId: '1:523933472075:web:597306910f74e14e2e44ce',
    messagingSenderId: '523933472075',
    projectId: 'gateguard-2064c',
    authDomain: 'gateguard-2064c.firebaseapp.com',
    storageBucket: 'gateguard-2064c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDlNYOjTAYTwxW1avB4tUo9YRVvXVynn8',
    appId: '1:523933472075:android:4ad744636eb2681c2e44ce',
    messagingSenderId: '523933472075',
    projectId: 'gateguard-2064c',
    storageBucket: 'gateguard-2064c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFU7CjqCbQGi5lvZBtnhP3dgT3-Q-b6Nc',
    appId: '1:523933472075:ios:215af1b8ebe942b82e44ce',
    messagingSenderId: '523933472075',
    projectId: 'gateguard-2064c',
    storageBucket: 'gateguard-2064c.firebasestorage.app',
    iosBundleId: 'com.example.gateguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFU7CjqCbQGi5lvZBtnhP3dgT3-Q-b6Nc',
    appId: '1:523933472075:ios:215af1b8ebe942b82e44ce',
    messagingSenderId: '523933472075',
    projectId: 'gateguard-2064c',
    storageBucket: 'gateguard-2064c.firebasestorage.app',
    iosBundleId: 'com.example.gateguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP_KYtLoBz0YOt9kmgaqZCyOx1HVMuKRc',
    appId: '1:523933472075:web:9eb6bac7760cad532e44ce',
    messagingSenderId: '523933472075',
    projectId: 'gateguard-2064c',
    authDomain: 'gateguard-2064c.firebaseapp.com',
    storageBucket: 'gateguard-2064c.firebasestorage.app',
  );
}
